let wineCategories = {
    wines: [
        {
            name: "white wine",
            types: [
                { name: "dry white wine",
                types:[
                    {name: "assyrtiko"},
                    {name: "pinot blanc"},
                    {name: "cortese"},
                    {name: "roussanne"},
                    {name: "moschofilero"},
                    {name: "muscadet"},
                    {name: "viognier"},
                    {name: "verdicchio"},
                    {name: "greco"},
                    {name: "marsanne"},
                    {name: "white burgundy"},
                    {name: "chardonnay"},
                    {name: "gruener veltliner"},
                    {name: "white rioja"},
                    {name: "frascati"},
                    {name: "gavi"},
                    {name: "l acadie blanc"},
                    {name: "trebbiano"},
                    {name: "sauvignon blanc"},
                    {name: "catarratto"},
                    {name: "albarino"},
                    {name: "arneis"},
                    {name: "verdejo"},
                    {name: "vermentino"},
                    {name: "soave"},
                    {name: "pinot grigio"},
                    {name: "dry riesling"},
                    {name: "torrontes"},
                ] },
                { name: "mueller thurgau" },
                { name: "grechetto" },
                { name: "gewurztraminer" },
                { name: "chenin blanc" },
                { name: "white bordeaux" },
                { name: "semillon" },
                { name: "riesling" },
                { name: "sauternes" },
                { name: "sylvaner" },
                { name: "lillet blanc" },
            ],
        },
        { name: "red wine" },
        { name: "rose wine" },
        { name: "sparkling wine" },
        { name: "sherry" },
        { name: "vermouth" },
        { name: "fruit wine" },
        { name: "mead" }
    ]
}

export default wineCategories;